[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["v4-template/lib"]
solc_version = "0.8.30"
evm_version = "cancun"
ffi = true
via_ir = false
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}, {access = "read-write", path = "./deployments/"}]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
